load("//build/utils:exec_alias_rules.bzl", "exec_transition_alias_opt")

exec_transition_alias_opt(
    name = "insta",
    actual = "@bindeps//:cargo-insta__cargo-insta",
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
