[package]
name = "edge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tracing = "0"
native-tls = "0"
tokio-native-tls = "0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
hyper = { version = "0", features = ["full"] }
tonic = { version = "0", features = ["tls"] }
chrono = { version = "0", default-features = false, features = ["clock"] }
prost = "0"
async-stream = "0"
futures = "0"
futures-util = "0"
bytes = "1"
async-trait = "0"
fred = { version = "6", features = ["enable-native-tls", "sentinel-client", "sentinel-auth", "subscriber-client"] }
url-parse = "1"
nix = "0"
sha2 = "0"
tokio-util = "0"
tokio-stream = "0"
serde_json = "1"
routerify = "3"
uuid = "1"
url = "2"

common = { path = "../../common" }

[build-dependencies]
tonic-build = "0"
prost-build = "0"

[dev-dependencies]
dotenvy = "0"
portpicker = "0"
serial_test = "2"
tempfile = "3"
