# You must change these to your own details.
[package]
name = "video-player"
description = "Scuffle Video Player"
version = "0.0.1"
authors = ["Troy Benson <troy@scuffle.tv>"]
categories = ["wasm"]
readme = "README.md"
license = "LICENSE.md"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
console_error_panic_hook = "0.1.7"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
bytes = "1.4.0"
anyhow = "1.0.72"
wasm-bindgen-futures = "0.4.37"
gloo-timers = { version = "0.2.6", features = ["futures"] }
js-sys = "0.3.64"
url = { version = "2.4.0", features = ["serde"] }
futures = "0.3.28"
tokio = { version = "1.29.1", features = ["sync", "macros"] }
tokio-stream = "0.1.14"
serde = { version = "1.0.183", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
tsify = "0.4.5"
serde_json = "1.0.104"
base64 = "0.21.2"
tracing-core = "0.1.31"

bytesio = { workspace = true }
h264 = { workspace = true }
mp4 = { workspace = true }

[dependencies.web-sys]
version = "0.3.64"
features = [
    "console",
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
    "HtmlVideoElement",
    "MediaSource",
    "SourceBuffer",
    "Url",
    "MediaSourceReadyState",
    "Event",
    "ErrorEvent",
    "TimeRanges",
    "HtmlMediaElement",
    "MediaStream",
    "Performance",
    "Window",
    "XmlHttpRequest",
    "XmlHttpRequestResponseType",
    "PerformanceResourceTiming",
    "PerformanceObserver",
    "PerformanceObserverInit",
    "PerformanceObserverEntryList",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
futures = "0.3.28"
js-sys = "0.3.64"
wasm-bindgen-futures = "0.4.37"
