# You must change these to your own details.
[package]
name = "player"
description = "Scuffle Video Player"
version = "0.1.0"
authors = ["Troy Benson <troy@scuffle.tv>"]
categories = ["wasm"]
readme = "README.md"
license = "LICENSE.md"
edition = "2021"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
strip = true
panic = "abort"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0"
console_error_panic_hook = "0"
tracing = "0"
tracing-subscriber = "0"
bytes = "1"
anyhow = "1"
wasm-bindgen-futures = "0"
gloo-timers = { version = "0", features = ["futures"] }
js-sys = "0"
url = { version = "2", features = ["serde"] }
futures = "0"
tokio = { version = "1", features = ["sync", "macros"] }
tokio-stream = "0"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0"
tsify = "0"
serde_json = "1"
h264 = { path = "../../video/codec/h264" }
base64 = "0"

bytesio = { path = "../../video/bytesio", default-features = false }
mp4 = { path = "../../video/container/mp4" }

[dependencies.web-sys]
version = "0"
features = [
    "console",
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
    "HtmlVideoElement",
    "MediaSource",
    "SourceBuffer",
    "Url",
    "MediaSourceReadyState",
    "Event",
    "ErrorEvent",
    "TimeRanges",
    "HtmlMediaElement",
    "MediaStream",
    "Performance",
    "Window",
    "XmlHttpRequest",
    "XmlHttpRequestResponseType",
    "PerformanceResourceTiming",
    "PerformanceObserver",
    "PerformanceObserverInit",
    "PerformanceObserverEntryList",
]

[dev-dependencies]
wasm-bindgen-test = "0"
futures = "0"
js-sys = "0"
wasm-bindgen-futures = "0"
