#![cfg_attr(coverage_nightly, coverage(off))]
// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub(crate) mod sql_types {
    /// The `device_algorithm` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "device_algorithm"))]
    pub struct DeviceAlgorithm;
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::DeviceAlgorithm;

    /// Representation of the `devices` table.
    ///
    /// (Automatically generated by Diesel.)
    devices (fingerprint) {
        /// The `fingerprint` column of the `devices` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        fingerprint -> Bytea,
        /// The `algorithm` column of the `devices` table.
        ///
        /// Its SQL type is `DeviceAlgorithm`.
        ///
        /// (Automatically generated by Diesel.)
        algorithm -> DeviceAlgorithm,
        /// The `public_key_data` column of the `devices` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        public_key_data -> Bytea,
        /// The `last_active_at` column of the `devices` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_active_at -> Timestamptz,
        /// The `created_at` column of the `devices` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `magic_link_requests` table.
    ///
    /// (Automatically generated by Diesel.)
    magic_link_requests (id) {
        /// The `id` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `email` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `code` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 5]
        code -> Varchar,
        /// The `expires_at` column of the `magic_link_requests` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `mfa_passkey_credentials` table.
    ///
    /// (Automatically generated by Diesel.)
    mfa_passkey_credentials (id) {
        /// The `id` column of the `mfa_passkey_credentials` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `mfa_passkey_credentials` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `credential_id` column of the `mfa_passkey_credentials` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        credential_id -> Bytea,
        /// The `name` column of the `mfa_passkey_credentials` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Nullable<Varchar>,
        /// The `credential` column of the `mfa_passkey_credentials` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        credential -> Jsonb,
        /// The `counter` column of the `mfa_passkey_credentials` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        counter -> Int8,
        /// The `last_used_at` column of the `mfa_passkey_credentials` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `mfa_recovery_codes` table.
    ///
    /// (Automatically generated by Diesel.)
    mfa_recovery_codes (id) {
        /// The `id` column of the `mfa_recovery_codes` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `mfa_recovery_codes` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `code_hash` column of the `mfa_recovery_codes` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        code_hash -> Varchar,
    }
}

diesel::table! {
    /// Representation of the `mfa_totp_credentials` table.
    ///
    /// (Automatically generated by Diesel.)
    mfa_totp_credentials (id) {
        /// The `id` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `name` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Nullable<Varchar>,
        /// The `url` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 1024]
        url -> Varchar,
        /// The `last_used_at` column of the `mfa_totp_credentials` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_used_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `organization_invitations` table.
    ///
    /// (Automatically generated by Diesel.)
    organization_invitations (id) {
        /// The `id` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `organization_id` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `email` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `invited_by_id` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        invited_by_id -> Uuid,
        /// The `expires_at` column of the `organization_invitations` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        expires_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `organization_member_policy_set_assignments` table.
    ///
    /// (Automatically generated by Diesel.)
    organization_member_policy_set_assignments (organization_id, user_id, policy_set_id) {
        /// The `organization_id` column of the `organization_member_policy_set_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `user_id` column of the `organization_member_policy_set_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `policy_set_id` column of the `organization_member_policy_set_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        policy_set_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `organization_members` table.
    ///
    /// (Automatically generated by Diesel.)
    organization_members (organization_id, user_id) {
        /// The `organization_id` column of the `organization_members` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `user_id` column of the `organization_members` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `invited_by_id` column of the `organization_members` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        invited_by_id -> Nullable<Uuid>,
        /// The `created_at` column of the `organization_members` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `inline_policy` column of the `organization_members` table.
        ///
        /// Its SQL type is `Nullable<Bytea>`.
        ///
        /// (Automatically generated by Diesel.)
        inline_policy -> Nullable<Bytea>,
    }
}

diesel::table! {
    /// Representation of the `organizations` table.
    ///
    /// (Automatically generated by Diesel.)
    organizations (id) {
        /// The `id` column of the `organizations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `organizations` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `owner_id` column of the `organizations` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        owner_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `pending_user_emails` table.
    ///
    /// (Automatically generated by Diesel.)
    pending_user_emails (email, user_id) {
        /// The `email` column of the `pending_user_emails` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `user_id` column of the `pending_user_emails` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `codes_sent` column of the `pending_user_emails` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        codes_sent -> Int4,
        /// The `last_sent_code_at` column of the `pending_user_emails` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_sent_code_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `policy_sets` table.
    ///
    /// (Automatically generated by Diesel.)
    policy_sets (id) {
        /// The `id` column of the `policy_sets` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `organization_id` column of the `policy_sets` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Nullable<Uuid>,
        /// The `data` column of the `policy_sets` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Bytea,
    }
}

diesel::table! {
    /// Representation of the `projects` table.
    ///
    /// (Automatically generated by Diesel.)
    projects (id) {
        /// The `id` column of the `projects` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `name` column of the `projects` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `organization_id` column of the `projects` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `role_member_assignments` table.
    ///
    /// (Automatically generated by Diesel.)
    role_member_assignments (organization_id, user_id, role_id) {
        /// The `organization_id` column of the `role_member_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `user_id` column of the `role_member_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `role_id` column of the `role_member_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        role_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `role_policy_set_assignments` table.
    ///
    /// (Automatically generated by Diesel.)
    role_policy_set_assignments (role_id, policy_set_id) {
        /// The `role_id` column of the `role_policy_set_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        role_id -> Uuid,
        /// The `policy_set_id` column of the `role_policy_set_assignments` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        policy_set_id -> Uuid,
    }
}

diesel::table! {
    /// Representation of the `roles` table.
    ///
    /// (Automatically generated by Diesel.)
    roles (id) {
        /// The `id` column of the `roles` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `organization_id` column of the `roles` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        organization_id -> Uuid,
        /// The `name` column of the `roles` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `description` column of the `roles` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `inline_policy_set` column of the `roles` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        inline_policy_set -> Bytea,
    }
}

diesel::table! {
    /// Representation of the `user_emails` table.
    ///
    /// (Automatically generated by Diesel.)
    user_emails (email) {
        /// The `email` column of the `user_emails` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `user_id` column of the `user_emails` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `created_at` column of the `user_emails` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `user_google_connections` table.
    ///
    /// (Automatically generated by Diesel.)
    user_google_connections (sub) {
        /// The `sub` column of the `user_google_connections` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        sub -> Varchar,
        /// The `user_id` column of the `user_google_connections` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `created_at` column of the `user_google_connections` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `user_sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    user_sessions (user_id, device_fingerprint) {
        /// The `user_id` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `device_fingerprint` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        device_fingerprint -> Bytea,
        /// The `token` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 32]
        token -> Varchar,
        /// The `token_expires_at` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        token_expires_at -> Timestamptz,
        /// The `refresh_expires_at` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        refresh_expires_at -> Timestamptz,
        /// The `last_login_at` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_login_at -> Timestamptz,
        /// The `created_at` column of the `user_sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `preferred_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        preferred_name -> Nullable<Varchar>,
        /// The `first_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        first_name -> Nullable<Varchar>,
        /// The `last_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        last_name -> Nullable<Varchar>,
        /// The `password_hash` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        password_hash -> Nullable<Varchar>,
        /// The `primary_email` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        primary_email -> Varchar,
        /// The `avatar_url` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        avatar_url -> Nullable<Varchar>,
    }
}

diesel::joinable!(magic_link_requests -> users (user_id));
diesel::joinable!(mfa_passkey_credentials -> users (user_id));
diesel::joinable!(mfa_recovery_codes -> users (user_id));
diesel::joinable!(mfa_totp_credentials -> users (user_id));
diesel::joinable!(organization_invitations -> organizations (organization_id));
diesel::joinable!(organization_invitations -> users (invited_by_id));
diesel::joinable!(organization_member_policy_set_assignments -> policy_sets (policy_set_id));
diesel::joinable!(organization_members -> organizations (organization_id));
diesel::joinable!(organizations -> users (owner_id));
diesel::joinable!(policy_sets -> organizations (organization_id));
diesel::joinable!(projects -> organizations (organization_id));
diesel::joinable!(role_policy_set_assignments -> policy_sets (policy_set_id));
diesel::joinable!(role_policy_set_assignments -> roles (role_id));
diesel::joinable!(roles -> organizations (organization_id));
diesel::joinable!(user_google_connections -> users (user_id));
diesel::joinable!(user_sessions -> devices (device_fingerprint));
diesel::joinable!(user_sessions -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    devices,
    magic_link_requests,
    mfa_passkey_credentials,
    mfa_recovery_codes,
    mfa_totp_credentials,
    organization_invitations,
    organization_member_policy_set_assignments,
    organization_members,
    organizations,
    pending_user_emails,
    policy_sets,
    projects,
    role_member_assignments,
    role_policy_set_assignments,
    roles,
    user_emails,
    user_google_connections,
    user_sessions,
    users,
);
