[package]
name = "scuffle-metrics"
version = "0.4.2"
authors = ["Scuffle <opensource@scuffle.cloud>"]
documentation = "https://docs.rs/scuffle-metrics"
edition = "2024"
keywords = ["metrics", "prometheus", "opentelemetry"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"
description = "Helper crate to instrument your code with metrics."

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[[example]]
name = "scuffle-metrics-derive"
path = "examples/derive.rs"
required-features = ["default"]

[[example]]
name = "scuffle-metrics-prometheus"
path = "examples/prometheus.rs"
required-features = ["default"]

[features]
default = ["prometheus"]
## Enables prometheus support
prometheus = ["dep:prometheus-client"]
## Enables tracing support
tracing = ["dep:tracing"]
## Enables changelog and documentation of feature flags
docs = ["dep:scuffle-changelog", "dep:document-features"]

[dependencies]
document-features = { optional = true, version = "0.2" }
opentelemetry = { default-features = false, features = ["metrics"], version = "0.30" }
opentelemetry_sdk = { default-features = false, features = ["experimental_metrics_custom_reader", "metrics"], version = "0.30" }
parking_lot = "0.12"
prometheus-client = { optional = true, version = "0.23" }
scuffle-changelog = { optional = true, path = "../changelog", version = "0.1.0" }
scuffle-metrics-derive = { path = "derive", version = "=0.4.2" }
tracing = { optional = true, version = "0.1" }

[dev-dependencies]
insta = "1.42.0"
postcompile = { path = "../postcompile" }

# For examples:
opentelemetry-stdout = "0.30"
tokio = { features = ["full"], version = "1" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
  "--cfg",
  "docsrs",
  "--sort-modules-by-appearance",
  "--generate-link-to-definition",
]

[package.metadata.xtask.powerset]
additive-features = [
  "prometheus",
  "tracing",
  "internal-logs",
  "default",
  "docs",
]

[package.metadata.sync-readme.rustdoc-mappings]
changelog = "./CHANGELOG.md"

[package.metadata.sync-readme.badges]
docs-rs = true
crates-io = true
license = true
codecov = true
