name: Setup Rust
description: Configures the Rust toolchain
inputs:
  toolchain:
    description: "The toolchain to use"
    required: true
    default: "stable"
  components:
    description: "The components to install"
    required: false
  shared-key:
    description: "The key to use for the shared cache"
    required: false
  tools:
    description: "The tools to install"
    required: false
  cache-backend:
    description: "The backend to use for the cache"
    required: false
    default: github
runs:
  using: "composite"
  steps:
    - uses: dtolnay/rust-toolchain@stable
      id: setup-rust
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.shared-key && inputs.cache-backend == 'github' }}
      with:
        prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
        shared-key: ${{ inputs.shared-key }}

    - name: Set up Rust cache
      if: ${{ inputs.shared-key && inputs.cache-backend == 'namespace' }}
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        cache: rust

    - uses: taiki-e/install-action@v2
      if: ${{ inputs.tools }}
      with:
        tool: ${{ inputs.tools }}
