load("//build/utils:exec_alias_rules.bzl", "exec_transition_alias_opt")

exec_transition_alias_opt(
    name = "mergiraf",
    actual = "@bindeps//:mergiraf__mergiraf",
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
