[package]
name = "flv"
version = "0.0.1"
edition = "2021"

[dependencies]
byteorder = "1"
bytes = "1"
num-traits = "0"
num-derive = "0"

bytesio = { path = "../../bytesio" }
av1 = { path = "../../codec/av1" }
h264 = { path = "../../codec/h264" }
h265 = { path = "../../codec/h265" }
aac = { path = "../../codec/aac" }
amf0 = { path = "../../utils/amf0" }
