[package]
name = "scufflecloud-video-api-traits"
version = "0.1.0"
authors = ["Scuffle <opensource@scuffle.cloud>"]
edition = "2024"
license = "AGPL-3.0"
publish = false
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
anyhow = "1"
db-types = { path = "../db-types", package = "scufflecloud-video-api-db-types" }
diesel = { version = "2", default-features = false }
diesel-async = { version = "0.7", default-features = false }
scuffle-batching = { path = "../../../../crates/batching" }

[package.metadata.sync-readme.badges]
docs-rs = false
crates-io = false
license = true
codecov = true
