version: "3.1"

name: "db-scuffle-dev"

services:
  cockroach:
    image: cockroachdb/cockroach:latest
    ports:
      - "5432:26257"
      - "8080:8080"
    command: start-single-node --insecure

  rmq:
    image: bitnami/rabbitmq:latest
    environment:
      RABBITMQ_USERNAME: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq
      RABBITMQ_VHOSTS: /scuffle
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  default:
    name: scuffle-dev
    external: true
