version: "3.1"

name: "db-scuffle-dev"

services:
  cockroach:
    image: ghcr.io/scuffletv/cockroach:latest
    ports:
      - "5432:26257"
      - "8080:8080"

  rmq:
    image: bitnami/rabbitmq:latest
    environment:
      RABBITMQ_USERNAME: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq
      RABBITMQ_VHOSTS: scuffle
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  default:
    name: scuffle-dev
    external: true
