[package]
name = "xtask"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
readme = "README.md"

[dependencies]
anyhow = "1.0"
cargo-platform = "0.3"
cargo_metadata = "0.23"
chrono = "0.4"
clap = { features = ["derive", "env"], version = "4.5.23" }
fmtools = "0.1"
hex = "0.4"
home = "0.5"
indent_write = "2.2.0"
minijinja = "2"
num_cpus = "1"
serde = "1"
serde_derive = "1"
serde_json = "1.0"
sha2 = "0.10"
toml_edit = { features = ["serde"], version = "0.23" }
tracing = "0.1"
tracing-subscriber = { features = ["env-filter"], version = "0.3" }
