load("//misc/utils:exec_alias_rules.bzl", "exec_transition_alias_opt")

exec_transition_alias_opt(
    name = "deny",
    actual = "@bindeps//:cargo-deny__cargo-deny",
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
