[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-3.0",
    "Apache-2.0 WITH LLVM-exception",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "MPL-2.0",
    "BSL-1.0",
    "CDLA-Permissive-2.0",
    "OpenSSL",
]

private.ignore = true
unused-allowed-license = "warn"
confidence-threshold = 0.95

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[advisories]
ignore = [
    # paste is unmaintained
    # todo: remove once aws-lc-rs is updated
    # https://github.com/aws/aws-lc-rs/issues/722
    "RUSTSEC-2024-0436",
    # This vulnerability does not affect us since we are not dealing with any private RSA keys at any time.
    # Therefore we can't leak any private information through a timing attack.
    "RUSTSEC-2023-0071",
]

[bans]
multiple-versions = "allow"
deny = [
    # AI Fork of serde_yaml
    "serde_yml",
]
