[package]
name = "redis-module-ext"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
redis-module = { git = "https://github.com/RedisLabsModules/redismodule-rs", rev = "v2.1.1" }
redis-module-ext-macros = { path = "./macros" }
fmtools = "0.1"
