[package]
name = "rust_analyzer_discover"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
readme = "README.md"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(bazel_runfiles)'] }

[dependencies]
anyhow = "1"
camino = { version = "1", features = ["serde1"] }
clap = { version = "4.5", features = ["derive", "env"] }
env_logger = "0.10"
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"

[package.metadata.sync-readme.badges]
docs-rs = false
crates-io = false
license = true
codecov = true
