[package]
name = "scufflecloud-core-db-types"
version = "0.1.0"
authors = ["Scuffle <opensource@scuffle.cloud>"]
edition = "2024"
license = "AGPL-3.0"
publish = false
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
bon = "3.5"
chrono = "0.4"
diesel = { version = "2", default-features = false }
diesel-derive-enum = { version = "3.0.0-beta.1", features = ["postgres"] }
id = { path = "../../id", package = "scufflecloud-id" }
ipnetwork = "0.21"
serde = "1"
serde_derive = "1"
serde_json = "1"
sha2 = "0.10"
thiserror = "2"
ulid = "1"
uuid = "1"

[package.metadata.sync-readme.badges]
docs-rs = false
crates-io = false
license = true
codecov = true
