[package]
name = "scuffle-opus"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/scuffle-h264"
description = "A pure Rust implementation of Opus ISOBMFF boxes"
keywords = ["opus", "audio", "codec", "isobmff"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
isobmff = { path = "../isobmff", version = "0.1.0" }
isobmff-derive = { path = "../isobmff/derive", version = "0.1.0" }
scuffle-bytes-util = { path = "../bytes-util", version = "0.2.0" }
scuffle-changelog = { optional = true, path = "../changelog", version = "0.1.0" }
document-features = { optional = true, version = "0.2" }
scuffle-workspace-hack.workspace = true

[features]
## Enables changelog and documentation of feature flags
docs = ["dep:scuffle-changelog", "dep:document-features"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
  "--cfg",
  "docsrs",
  "--sort-modules-by-appearance",
  "--generate-link-to-definition",
]

[package.metadata.xtask.powerset]
additive-features = ["docs", "serde"]

[package.metadata.cargo-sync-rdme.rustdoc.mappings]
changelog = "./CHANGELOG.md"

[package.metadata.cargo-sync-rdme.badge]
style = "flat-square"

[package.metadata.cargo-sync-rdme.badge.badges]
license = true
docs-rs = true
crates-io = true
github-actions = { workflows = "ci.yaml" }
codecov = true
