version: "3.1"

name: "db-scuffle-dev"

services:
  cockroach:
    image: ghcr.io/scuffletv/ci/cockroach:latest
    pull_policy: "always"
    command: start-single-node --insecure --store=type=mem,size=0.25 --advertise-addr=0.0.0.0
    ports:
      - "5432:26257"
      - "8080:8080"

  nats:
    image: ghcr.io/scuffletv/ci/nats:latest
    pull_policy: "always"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    command:
      - "-js"

  minio:
    image: ghcr.io/scuffletv/ci/minio:latest
    pull_policy: "always"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ACCESS_KEY=root"
      - "MINIO_SECRET_KEY=scuffle123"
    command: server /export --console-address ":9001"

  createbuckets:
    image: minio/mc:latest
    pull_policy: "always"
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      set -eux;
      /usr/bin/mc config host add myminio http://minio:9000 root scuffle123;
      /usr/bin/mc rb --force myminio/scuffle-video || true;
      /usr/bin/mc rb --force myminio/scuffle-image-processor || true;
      /usr/bin/mc rb --force myminio/scuffle-image-processor-public || true;
      /usr/bin/mc mb myminio/scuffle-video;
      /usr/bin/mc mb myminio/scuffle-image-processor;
      /usr/bin/mc mb myminio/scuffle-image-processor-public;
      /usr/bin/mc anonymous set download myminio/scuffle-video;
      /usr/bin/mc anonymous set download myminio/scuffle-image-processor-public;
      exit 0;
      "

  redis:
    image: ghcr.io/scuffletv/ci/redis:latest
    pull_policy: "always"
    ports:
      - "6379:6379"
