[package]
name = "isobmff-derive"
version = "0.1.0"
edition = "2024"
description = "Derive macro for isobmff::IsoBox"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/isobmff-derive"
license = "MIT OR Apache-2.0"
keywords = ["isobmff", "mp4", "video", "container", "iso-14496-12", "derive", "macros"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[lib]
proc-macro = true

[dependencies]
syn = "2.0.100"
proc-macro2 = "1.0.95"
quote = "1.0.40"
darling = "0.20.11"
scuffle-bytes-util.workspace = true
scuffle-workspace-hack.workspace = true
