[package]
name = "isobmff-derive"
version = "0.1.0"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[lib]
proc-macro = true

[dependencies]
syn = "2.0.100"
proc-macro2 = "1.0.95"
quote = "1.0.40"
darling = "0.20.11"
scuffle-workspace-hack.workspace = true
