[package]
name = "sync_readme"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
camino = "1"
cargo_toml = "0.22"
clap = { version = "4.5", features = ["derive", "env"] }
pulldown-cmark = "0.13"
pulldown-cmark-to-cmark = "21"
regex = "1"
rustdoc-types = { version = "0.55", features = ["rustc-hash"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
sync_readme_common.path = "common"
toml = "0.9"

[package.metadata.sync-readme.badges]
license = true
