[package]
name = "sync_readme_test_runner"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
camino = "1"
clap = { version = "4.5", features = ["derive", "env"] }
console = "0.16"
serde_json = "1"
similar = { version = "2.7", features = ["inline"] }
sync_readme_common.path = "../common"

[package.metadata.sync-readme.badges]
license = true
