[package]
name = "tinc-integration-tests"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dev-dependencies]
bytes = "1"
http = "1"
http-body-util = "0.1"
insta = { features = ["json"], version = "1" }
prost = "0.14"
prost-types = "0.14"
rand = "0.9"
serde = "1"
serde_json = "1"
tinc = { path = ".." }
tokio = { features = ["full"], version = "1" }
tonic = "0.14"
tower = "0.5"

[build-dependencies]
prost-build = "0.14"
tinc-build = { path = "../build", version = "0.2" }
