[package]
name = "tinc-integration-tests"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dev-dependencies]
bytes = "1"
http = "1"
http-body-util = "0.1"
insta = { features = ["json"], version = "1.30.0" }
prost = "0.13.5"
prost-types = "0.13.5"
rand = "0.9"
scuffle-workspace-hack.workspace = true
serde = "1.0.215"
serde_json = "1.0.115"
tinc = { path = ".." }
tokio = { features = ["full"], version = "1.4.2" }
tonic = "0.13"
tower = "0.5"

[build-dependencies]
prost-build = "0.13.5"
tinc-build = { path = "../build", version = "0.1.1" }
