load("//misc/utils/rust:package.bzl", "scuffle_package")
load("//misc/utils/rust:manifest.bzl", "cargo_toml")

cargo_toml()

scuffle_package(
    crate_name = "rustdoc_wrapper",
    crate_type = "bin",
    tags = ["manual"],
)
