[package]
name = "rustdoc_wrapper"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
camino = { version = "1", features = ["serde1"] }
camino-tempfile = "1.4"
clap = { version = "4.5", features = ["derive", "env"] }

[package.metadata.sync-readme.badges]
license = true
