[package]
name = "scufflecloud-core-cedar"
version = "0.1.0"
authors = ["Scuffle <opensource@scuffle.cloud>"]
edition = "2024"
license = "AGPL-3.0"
publish = false
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"

[dependencies]
base64 = "0.22"
cedar-policy = "4.5"
const_panic = "0.2"
core-db-types = { path = "../db-types", package = "scufflecloud-core-db-types" }
core-traits = { path = "../traits", package = "scufflecloud-core-traits" }
konst = { version = "0.4", features = ["iter"] }
pb = { path = "../../proto", package = "scufflecloud-proto" }
serde = "1"
serde_derive = "1"
serde_json = "1"
tonic = "0.14"
