[package]
name = "scufflecloud-core-cedar"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
cedar-policy = "4.5"
core-db-types = { path = "../db-types", package = "scufflecloud-core-db-types" }
core-traits = { path = "../traits", package = "scufflecloud-core-traits" }
pb = { path = "../../proto", package = "scufflecloud-proto" }
serde = "1"
serde_derive = "1"
serde_json = "1"
tonic = "0.14"
