[package]
name = "diesel_migration_patcher"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
camino = { version = "1", features = ["serde1"] }
clap = { version = "4.5", features = ["derive", "env"] }
env_logger = "0.11"
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
