[package]
name = "scufflecloud-video-api"
version = "0.1.0"
authors = ["Scuffle <opensource@scuffle.cloud>"]
edition = "2024"
license = "AGPL-3.0"
publish = false
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"
description = "Video API server for scuffle.cloud"

[[bin]]
name = "scufflecloud-video-api-standalone"
path = "bin/standalone/main.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
anyhow = "1"
axum = "0.8"
db-types = { path = "./db-types", package = "scufflecloud-video-api-db-types" }
diesel = { features = ["uuid"], version = "2" }
diesel-async = { features = ["async-connection-wrapper", "bb8", "postgres"], version = "0.7" }
ext-traits = { path = "../../ext-traits", package = "scufflecloud-ext-traits" }
pb = { path = "../../proto", package = "scufflecloud-proto" }
petname = { version = "2", default-features = false, features = ["default-words", "default-rng"] }
rustls = "0.23"
scuffle-batching = { path = "../../../crates/batching" }
scuffle-bootstrap = { path = "../../../crates/bootstrap" }
scuffle-bootstrap-telemetry = { features = ["opentelemetry-logs", "opentelemetry-traces"], path = "../../../crates/bootstrap-telemetry" }
scuffle-context = { path = "../../../crates/context" }
scuffle-http = { features = ["tracing", "tls-rustls"], path = "../../../crates/http" }
scuffle-settings = { features = ["all-formats", "bootstrap"], path = "../../../crates/settings" }
scuffle-signal = { features = ["bootstrap"], path = "../../../crates/signal" }
serde = "1"
serde_derive = "1"
smart-default = "0.7"
swagger-ui-dist = "5"
tinc = { path = "../../../crates/tinc" }
tonic = { version = "0.14", features = ["tls-aws-lc"] }
tonic-reflection = "0.14"
tonic-types = "0.14"
tonic-web = "0.14"
tower-http = { features = ["cors", "trace"], version = "0.6" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
video-api-traits = { path = "./traits", package = "scufflecloud-video-api-traits" }

[package.metadata.sync-readme.badges]
docs-rs = false
crates-io = false
license = true
codecov = true
