[[scuffle-amf0]]
category = "fix"
description = "Fix amf0 deserialization to abide by better deserialization standards"
authors = ["@philipch07", "@TroyKomodo"]

[[scuffle-amf0]]
category = "feat"
description = "Add an Amf0Value deserializer"
authors = ["@philipch07", "@TroyKomodo"]

[[scuffle-util-bytes]]
category = "feat"
description = "Add an `IntoDeserializer` implementation for `StringCow`"
authors = ["@TroyKomodo"]
