[[scuffle-bytes-util]]
category = "feat"
description = "implement the zero copy reader trait for mutable references of zero copy readers"
breaking = true
authors = ["@lennartkloock"]

[[scuffle-bytes-util]]
category = "feat"
description = "add ability to limit number of zero copy bytes read"
authors = ["@lennartkloock"]

[[scuffle-av1]]
category = "chore"
description = "update to use isobmff crate and new zero copy traits"
breaking = true
authors = ["@lennartkloock"]

[[scuffle-h264]]
category = "chore"
description = "update to use isobmff crate and new zero copy traits"
breaking = true
authors = ["@lennartkloock"]

[[scuffle-h265]]
category = "chore"
description = "update to use isobmff crate and new zero copy traits"
breaking = true
authors = ["@lennartkloock"]

[[scuffle-transmuxer]]
category = "chore"
description = "update to use isobmff crate"
breaking = true
authors = ["@lennartkloock"]
