[[postcompile]]
category = "chore"
description = "bumped internal deps"
authors = ["@TroyKomodo"]

[[scuffle-batching]]
category = "chore"
description = "bumped internal deps"
authors = ["@TroyKomodo"]

[[scuffle-bootstrap]]
category = "chore"
description = "bumped internal deps"
authors = ["@TroyKomodo"]

[[scuffle-metrics]]
category = "chore"
description = "bumped internal deps"
authors = ["@TroyKomodo"]
