[[scuffle-bytes-util]]
category = "chore"
description = "fix clippy::manual_is_multiple_of"
authors = ["@lennartkloock"]

[[scuffle-expgolomb]]
category = "chore"
description = "fix clippy::manual_is_multiple_of"
authors = ["@lennartkloock"]

[[scuffle-metrics]]
category = "chore"
description = "fix clippy::manual_is_multiple_of"
authors = ["@lennartkloock"]

[[tinc]]
category = "chore"
description = "fix clippy::manual_is_multiple_of"
authors = ["@lennartkloock"]
