blank_issues_enabled: false
contact_links:
  - name: Scuffle Discord
    url: https://scuffle.tv/discord
    about: Join our Discord for general questions as well as direct contact with the developers 
