load("//build/utils:package.bzl", "scuffle_package")
load("//build/utils:cargo_toml.bzl", "cargo_toml")

cargo_toml()

# scuffle_package(
#     name = "fix",
#     crate_name = "clippy-runner",
#     crate_type = "bin",
#     tags = ["manual"],
#     visibility = ["//visibility:public"],
# )
