[package]
name = "cargo-sync-rdme"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
rustfix = "0.9"
camino = "1"
env_logger = "0.11"
log = "0.4"
serde_json = "1"
miette = "7.6"
pulldown-cmark = "0.13"
tempfile = "3.20"
tracing = "0.1"
thiserror = "2"
serde_derive = "1"
serde = "1"
url = "1"
rustdoc-types = { version = "0.41", features = ["rustc-hash"] }
serde_norway = "0.9"
semver = "1"
toml = "0.9"
pulldown-cmark-to-cmark = "21"
clap = { version = "4.5", features = ["derive", "env"] }

[dev-dependencies]
indoc = "2.0.6"
