[package]
name = "scuffle-cedar-policy"
version = "0.1.0"
authors = ["Scuffle <opensource@scuffle.cloud>"]
documentation = "https://docs.rs/scuffle-cedar-policy"
edition = "2024"
keywords = ["codgen", "cedar"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"
description = "Some extensions to the cedar-policy crate."

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
bon = "3"
cedar-policy = "4"
cedar-policy-core = "4"
const_panic = "0.2"
document-features = { optional = true, version = "0.2" }
konst = "0.4"
scuffle-changelog = { optional = true, version = "0.1", path = "../changelog" }
serde = "1"
serde_derive = "1"
serde_json = "1"
smol_str = { version = "0.3", features = ["serde"] }
thiserror = "2"

[features]
docs = ["dep:scuffle-changelog", "dep:document-features"]

[package.metadata.sync-readme.rustdoc-mappings]
changelog = "./CHANGELOG.md"

[package.metadata.sync-readme.badges]
docs-rs = true
crates-io = true
license = true
codecov = true
