[package]
name = "scufflecloud-core"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"
description = "Authentication/Core server for scuffle.cloud"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
publish = false

[[bin]]
name = "scufflecloud-core"
path = "src/bin/standalone.rs"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
diesel = { version = "2.2.10", features = ["chrono"] }
diesel-async = { version = "0.5.2", features = ["postgres", "bb8", "async-connection-wrapper"] }
pb = { package = "scufflecloud-proto", path = "../proto" }
scuffle-bootstrap = "0.1.5"
scuffle-context = "0.1.5"
scuffle-http = { version = "0.3.2", features = ["tracing"] }
scuffle-signal = { features = ["bootstrap"], version = "0.3.3" }
scuffle-settings = { features = ["bootstrap", "all-formats"], version = "0.1.4" }
serde = "1.0.219"
serde_derive = "1.0.219"
smart-default = "0.7.1"
tinc = { path = "../../crates/tinc" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tonic = "0.13.1"

scuffle-workspace-hack.workspace = true

[package.metadata.cargo-sync-rdme.badge]
style = "flat-square"

[package.metadata.cargo-sync-rdme.badge.badges]
license = true
docs-rs = false
crates-io = false
github-actions = { workflows = "ci.yaml" }
codecov = true
