[package]
name = "scufflecloud-core"
version = "0.1.0"
authors = ["Scuffle <opensource@scuffle.cloud>"]
edition = "2024"
license = "AGPL-3.0"
publish = false
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"
description = "Authentication/Core server for scuffle.cloud"

[[bin]]
name = "scufflecloud-core"
path = "src/bin/standalone.rs"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
axum = "0.8.4"
diesel = { features = ["chrono"], version = "2.2.10" }
diesel-async = { features = ["async-connection-wrapper", "bb8", "postgres"], version = "0.5.2" }
pb = { package = "scufflecloud-proto", path = "../proto" }
scuffle-bootstrap = "0.1.5"
scuffle-context = "0.1.5"
scuffle-http = { features = ["tracing"], version = "0.3.2" }
scuffle-settings = { features = ["all-formats", "bootstrap"], version = "0.1.4" }
scuffle-signal = { features = ["bootstrap"], version = "0.3.3" }
serde = "1.0.219"
serde_derive = "1.0.219"
smart-default = "0.7.1"
tinc = { path = "../../crates/tinc" }
tonic = "0.13.1"
tower-http = { features = ["cors"], version = "0.6.6" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[package.metadata.sync-readme.badges]
docs-rs = false
crates-io = false
license = true
codecov = true
