[package]
name = "sync_readme_fixer"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
camino = "1"
clap = { version = "4.5", features = ["derive", "env"] }
env_logger = "0.11"
log = "0.4"
serde_json = "1"
sync_readme_common.path = "../../../build/utils/rust/sync_readme/common"
