DROP TABLE IF EXISTS "magic_link_requests" CASCADE;
DROP TABLE IF EXISTS "user_sessions" CASCADE;
DROP TABLE IF EXISTS "devices" CASCADE;
DROP TYPE IF EXISTS "device_algorithm" CASCADE;
DROP DOMAIN IF EXISTS "sha256" CASCADE;
