load("//build/utils:exec_alias_rules.bzl", "exec_transition_alias_opt")

exec_transition_alias_opt(
    name = "dprint",
    actual = "@bindeps//:dprint__dprint",
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
