[package]
name = "tinc-pb-prost"
version = "0.2.0"
edition = "2024"
description = "Protobuf generated schama for tinc"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/tinc-pb"
license = "MIT OR Apache-2.0"
keywords = ["grpc", "protobuf", "prost", "codegen"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[features]
## Enables documentation of feature flags
docs = ["dep:document-features"]

[dependencies]
document-features = { optional = true, version = "0.2" }
prost = "0.14"
prost-types = "0.14"

[build-dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
prost-build = "0.14"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
  "--cfg",
  "docsrs",
  "--sort-modules-by-appearance",
  "--generate-link-to-definition",
]

[package.metadata.xtask.powerset]
additive-features = ["docs"]

[package.metadata.xtask.release]
group = "tinc"

[package.metadata.sync-readme]
badge-style = "flat-square"

[package.metadata.sync-readme.rustdoc-mappings]
changelog = "./CHANGELOG.md"
Annotations = "./annotations.proto"

[package.metadata.sync-readme.badges]
docs-rs = true
crates-io = true
license = true
codecov = true
