filegroup(
    name = "flv",
    srcs = glob(["*.flv"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "mp4",
    srcs = glob(["*.mp4"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "pem",
    srcs = glob(["*.pem"]),
    visibility = ["//visibility:public"],
)
