[package]
name = "diesel_migration_copy"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
camino = { version = "1", features = ["serde1"] }
clap = { version = "4.5", features = ["derive", "env"] }
serde = "1"
serde_json = "1"
