load("//build/tools:package.bzl", "scuffle_package")

exports_files(["Cargo.toml"])

scuffle_package(
    crate_name = "clippy-runner",
    crate_type = "bin",
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
