[package]
name = "clippy_fixer"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
rustfix = "0.9"
camino = "1"
env_logger = "0.11"
log = "0.4"
serde_json = "1"
clap = { version = "4.5", features = ["derive", "env"] }
