#![cfg_attr(coverage_nightly, coverage(off))]
// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `streams` table.
    ///
    /// (Automatically generated by Diesel.)
    streams (id) {
        /// The `id` column of the `streams` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `project_id` column of the `streams` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        project_id -> Uuid,
        /// The `name` column of the `streams` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
    }
}
