[package]
name = "common"
version = "0.1.0"
edition = "2021"
authors = ["Scuffle <opensource@scuffle.tv>"]
description = "Scuffle Common Library"

[dependencies]
log = "0"
http = "0"
tower = "0"
config = "0"
anyhow = "1"
futures = "0"
tracing = "0"
arc-swap = "1"
tokio-util = "0"
async-trait = "0"
async-stream = "0"
tonic = { version = "0", features = ["tls"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
lapin = { version = "2.0.3", features = ["native-tls"] }
tracing-log = { version = "0", features = ["env_logger"] }
trust-dns-resolver = { version = "0", features = ["tokio-runtime"] }
tracing-subscriber = { version = "0", features = ["fmt", "env-filter", "json"] }

[dev-dependencies]
prost = "0"
tempfile = "3"
portpicker = "0"

[build-dependencies]
tonic-build = "0"
