[package]
name = "common"
version = "0.0.1"
edition = "2021"
authors = ["Scuffle <opensource@scuffle.tv>"]
description = "Scuffle Common Library"

[features]
logging = ["dep:log", "dep:tracing", "dep:tracing-log", "dep:tracing-subscriber", "dep:arc-swap", "dep:anyhow", "dep:once_cell", "dep:thiserror", "dep:serde"]
grpc = ["dep:tonic", "dep:anyhow", "dep:async-trait", "dep:futures", "dep:http", "dep:tower", "dep:trust-dns-resolver", "dep:tracing"]
context = ["dep:tokio", "dep:tokio-util"]
prelude = ["dep:tokio"]
signal = []
macros = []
config = ["dep:config", "dep:serde", "logging"]

default = ["logging", "grpc", "context", "prelude", "signal", "macros", "config"]

[dependencies]
log = { version = "0.4.19", optional = true }
http = { version = "0.2.9", optional = true }
tower = { version = "0.4.13", optional = true }
config = { workspace = true, optional = true }
anyhow = { version = "1.0.72", optional = true }
futures = { version = "0.3.28", optional = true }
tracing = { version = "0.2.0", optional = true, git = "https://github.com/tokio-rs/tracing.git" }
arc-swap = { version = "1.6.0", optional = true }
tokio-util = { version = "0.7.8", optional = true }
async-trait = { version = "0.1.72", optional = true }
tonic = { version = "0.9.2", features = ["tls"], optional = true }
tokio = { version = "1.29.1", features = ["sync", "rt"], optional = true }
serde = { version = "1.0.183", features = ["derive"], optional = true }
tracing-log = { version = "0.2.0", features = ["env_logger"], optional = true, git = "https://github.com/tokio-rs/tracing.git" }
once_cell = { version = "1.18.0", optional = true }
trust-dns-resolver = { version = "0.22.0", features = ["tokio-runtime"], optional = true }
tracing-subscriber = { version = "0.3.0", features = ["fmt", "env-filter", "json"], optional = true, git = "https://github.com/tokio-rs/tracing.git" }
thiserror = { version = "1.0.44", optional = true }

[dev-dependencies]
prost = "0.11.9"
tempfile = "3.7.1"
portpicker = "0.1.1"

[build-dependencies]
tonic-build = "0.9.2"
