name: Semver-checks
runs:
  using: "composite"
  steps:
    - name: Run xtask semver checks (against main branch)
      id: semver_checks
      shell: bash
      env:
        RUSTFLAGS: "--cfg reqwest_unstable"
      run: |
        result=$(cargo xtask semver-checks --disable-hakari)
        echo "checks_output<<EOF" >> $GITHUB_OUTPUT
        echo "$result" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Add/update PR comment
      uses: thollander/actions-comment-pull-request@v1
      with:
        # github-token: ${{ secrets.GITHUB_TOKEN }}
        message: ${{ steps.semver_checks.outputs.checks_output }}