name: Docs.rs
inputs:
  pr_number:
    description: "The PR number"
    required: true
  artifact_name:
    description: "The name of the artifact to upload"
    required: false
  deploy_docs:
    description: "Whether to deploy the docs"
    required: true
    default: false
runs:
  using: "composite"
  steps:
    - name: Build docs
      shell: bash
      env:
        RUSTDOCFLAGS: "-Dwarnings --cfg docsrs --sort-modules-by-appearance --generate-link-to-definition --enable-index-page -Zunstable-options"
      run: |
        set -xeo pipefail
        cargo xtask release generate-pr --no-changelog-bump
        cargo doc --no-deps --all-features

    - name: Insert custom html for PR
      shell: bash
      run: python3 .github/scripts/patch-docs.py --repo-url='${{ github.event.repository.html_url }}' --commit-hash='${{ env.SHA }}' --pr-number='${{ inputs.pr_number || '' }}'

    - name: Upload docs
      uses: actions/upload-artifact@v4
      if: ${{ inputs.artifact_name }}
      with:
        name: ${{ inputs.artifact_name }}
        path: target/doc

    - name: Deploy
      if: ${{ inputs.deploy_docs == 'true' }}
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ env.CF_DOCS_API_KEY }}
        packageManager: npm
        accountId: ${{ env.CF_DOCS_ACCOUNT_ID }}
        command: pages deploy --project-name=scuffle-docrs --branch=pr/${{ inputs.pr_number }} --commit-hash=${{ env.SHA }} --commit-dirty=true ./target/doc
