[package]
name = "scuffle-metrics-derive"
version = "0.4.2"
authors = ["Scuffle <opensource@scuffle.cloud>"]
documentation = "https://docs.rs/scuffle-metrics-derive"
edition = "2024"
keywords = ["metrics", "derive", "macros"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"
description = "Derive macros for scuffle-metrics."

[lib]
proc-macro = true

[dependencies]
darling = "0.21"
proc-macro2 = "1"
quote = "1"
syn = { features = ["full"], version = "2" }

[dev-dependencies]
# scuffle-metrics = { path = ".." }

[package.metadata.xtask.release]
group = "scuffle-metrics"

[package.metadata.sync-readme.rustdoc-mappings]
changelog = "./CHANGELOG.md"

[package.metadata.sync-readme.badges]
docs-rs = true
crates-io = true
license = true
codecov = true
