alias(
    name = "cargo",
    actual = "//tools/cargo",
    tags = ["manual", "no-cache"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "run_under",
    srcs = [":run_under.sh"],
    tags = ["manual", "no-cache"],
    visibility = ["//visibility:public"],
)
