name: Release-checks
inputs:
  pr_number:
    description: "The PR number"
    required: true
runs:
  using: "composite"
  steps:
    - name: Fetch History
      shell: bash
      run: |
        git fetch --unshallow

    - name: Run release check
      id: semver_checks
      shell: bash
      continue-on-error: true
      env:
        RUSTFLAGS: "--cfg reqwest_unstable"
      run: |
        CMD="cargo xtask release check --exit-status"

        if [ "${{ inputs.pr_number }}" != "" ]; then
          CMD="$CMD --pr-number ${{ inputs.pr_number }}"
        fi

        # Execute the command, capturing stderr and stdout with tee
        bash -c "$CMD" 2> >(tee /tmp/.release-check.stderr >&2) 1> >(tee /tmp/.release-check.stdout)

    - name: PR Body
      shell: bash
      run: |
        {
          cat /tmp/.release-check.stdout
          printf '\n\n<details><summary>cargo xtask release check</summary>\n\n`````\n'
          sed -E "s/\x1B\[[0-9;]*[mK]//g" /tmp/.release-check.stderr
          printf '`````\n\n</details>'
        } | tee /tmp/.release-checks-body $GITHUB_STEP_SUMMARY

    - name: Add/update PR comment
      # skip commenting the summary on forked PRs
      if: ${{ !github.event.pull_request.head.repo.fork && inputs.pr_number != null }}
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: /tmp/.release-checks-body
        pr-number: ${{ inputs.pr_number }}
        comment-tag: semver-checks

    - name: Fail
      if: ${{ steps.semver_checks.outcome == 'failure' }}
      shell: bash
      run: |
        echo "A package versions not up-to-date"
        exit 1
