name: Setup bazel
inputs:
  build_buddy_token:
    required: true
  lookup-only:
    required: false
    default: "false"
outputs:
  cache-hit:
    value: ${{ steps.restore.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - uses: bazel-contrib/setup-bazel@0.15.0
      with:
        bazelisk-cache: true
        repository-cache: false
        bazelrc: |
          build --bes_results_url=https://scuffle.buildbuddy.io/invocation/
          build --bes_backend=grpcs://scuffle.buildbuddy.io
          build --remote_cache=grpcs://scuffle.buildbuddy.io
          build --remote_timeout=10m
          build --build_metadata=ROLE=CI
          build --build_metadata=VISIBILITY=PUBLIC
          build --remote_header=x-buildbuddy-api-key=${{ inputs.build_buddy_token }}
          build --color=yes
          build --jobs=250
          common --remote_max_connections=500
          build --nokeep_going
          common --announce_rc
          common --experimental_async_execution
          common --disk_cache=""
          common --repository_cache=~/.cache/bazel-repo

    - name: Cache repository
      uses: actions/cache/restore@v4
      id: restore
      with:
        path: ~/.cache/bazel-repo
        key: bazel-repo-v2-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('MODULE.bazel.lock') }}
        restore-keys: bazel-repo-v2-${{ runner.os }}-${{ runner.arch }}-
        lookup-only: ${{ inputs.lookup-only }}

    - name: Setup path
      shell: bash
      run: echo "$GITHUB_WORKSPACE/tools/scripts" >> $GITHUB_PATH
