[package]
name = "postcompile"
version = "0.3.3"
authors = ["Scuffle <opensource@scuffle.cloud>"]
build = "build.rs"
documentation = "https://docs.rs/postcompile"
edition = "2024"
keywords = ["postcompile", "snapshot", "test", "proc-macro"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"
description = "Helper crate for post-compiling Rust code."

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(trybuild_no_target)', 'cfg(postcompile_no_target)', 'cfg(coverage_nightly)', 'cfg(valgrind)'] }

[features]
## Enables changelog and documentation of feature flags
docs = ["dep:scuffle-changelog", "dep:document-features"]

[dependencies]
cargo-manifest = "0.19"
cargo_metadata = "0.21"
document-features = { optional = true, version = "0.2" }
prettyplease = "0.2"
regex = "1"
scuffle-changelog = { optional = true, path = "../changelog", version = "0.1.0" }
serde = "1"
serde_derive = "1"
serde_json = "1"
syn = "2"
target-triple = "0.1"
toml = "0.9"

[dev-dependencies]
insta = "1.42.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
    "--sort-modules-by-appearance",
    "--generate-link-to-definition",
]

[package.metadata.xtask.powerset]
additive-features = ["docs"]

[package.metadata.sync-readme.rustdoc-mappings]
changelog = "./CHANGELOG.md"

[package.metadata.sync-readme.badges]
docs-rs = true
crates-io = true
license = true
codecov = true
