alias(
    name = "clippy",
    actual = "//tools/cargo/clippy",
    tags = ["manual"]
)

alias(
    name = "fmt",
    actual = "//tools/cargo/fmt",
    tags = ["manual"]
)

alias(
    name = "vendor",
    actual = "//tools/cargo/vendor",
    tags = ["manual"]
)
