alias(
    name = "deny",
    actual = "//tools/cargo/deny",
    tags = ["manual", "no-cache"],
    visibility = ["//visibility:public"],
)

alias(
    name = "vendor",
    actual = "//tools/cargo/vendor",
    tags = ["manual", "no-cache"],
    visibility = ["//visibility:public"],
)

alias(
    name = "cargo",
    actual = "@rules_rust//tools/upstream_wrapper:cargo",
    tags = ["manual", "no-cache"],
    visibility = ["//visibility:public"],
)
