alias(
    name = "clippy",
    actual = "//tools/cargo/clippy",
    tags = ["manual", "no-cache"]
)

alias(
    name = "fmt",
    actual = "//tools/cargo/fmt",
    tags = ["manual", "no-cache"]
)

alias(
    name = "vendor",
    actual = "//tools/cargo/vendor",
    tags = ["manual", "no-cache"]
)

alias(
    name = "cargo",
    actual = "@rules_rust//tools/upstream_wrapper:cargo",
    tags = ["manual", "no-cache"],
)
