[package]
name = "scuffle-http"
version = "0.3.2"
authors = ["Scuffle <opensource@scuffle.cloud>"]
documentation = "https://docs.rs/scuffle-http"
edition = "2024"
keywords = ["http", "server", "http1", "http2", "http3"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/scufflecloud/scuffle"
description = "A high-performance HTTP server supporting HTTP/1.1, HTTP/2, and HTTP/3."

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[[example]]
name = "scuffle-http-echo"
path = "examples/echo.rs"
required-features = ["default"]

[[example]]
name = "scuffle-http-echo-tls"
path = "examples/echo_tls.rs"
required-features = ["default", "tls-rustls", "http3"]

[[example]]
name = "scuffle-http-axum"
path = "examples/axum.rs"
required-features = ["default", "tls-rustls", "http3", "tower", "tracing"]

[[example]]
name = "scuffle-http-webtransport"
path = "examples/webtransport.rs"
required-features = ["default", "tls-rustls", "http3", "webtransport", "tracing"]

[features]
default = ["http1", "http2", "tower"]
## Enables tracing support
tracing = [
    "dep:tracing",
    "quinn?/log",
    "h3-quinn?/tracing",
    "h3?/tracing",
    "tokio-rustls?/logging",
]
## Enables http1 support
http1 = [
    "dep:hyper",
    "dep:hyper-util",
    "dep:libc",
    "hyper/http1",
    "hyper-util/http1",
]
## Enabled http2 support
http2 = [
    "dep:hyper",
    "dep:hyper-util",
    "dep:libc",
    "hyper/http2",
    "hyper-util/http2",
]
## Enables http3 support
http3 = ["dep:quinn", "dep:h3-quinn", "dep:h3"]
## Enables WebTransport over HTTP/3 support
webtransport = ["dep:h3-webtransport", "dep:h3-datagram", "h3-quinn?/datagram"]
## Enables tls via rustls
tls-rustls = ["dep:tokio-rustls"]
## Alias for ["http3", "tls-rustls"]
http3-tls-rustls = ["http3", "tls-rustls"]
## Enables tower service support
tower = ["dep:tower"]
## Enables changelog and documentation of feature flags
docs = ["dep:scuffle-changelog", "dep:document-features"]

[dependencies]
bon = "3"
futures = { default-features = false, features = ["alloc"], version = "0.3" }
pin-project-lite = "0.2"
scuffle-context = { path = "../context", version = "0.1" }
thiserror = "2"
tokio = "1"

# HTTP parsing
bytes = "1"
http = "1"
http-body = "1"

# Tracing
tracing = { optional = true, version = "0.1" }

# HTTP/1.1, HTTP/2
hyper = { default-features = false, features = ["server"], optional = true, version = "1" }
hyper-util = { default-features = false, features = ["server", "tokio"], optional = true, version = "0.1" }
libc = { default-features = false, optional = true, version = "0.2" }

# QUIC + HTTP/3
h3 = { default-features = false, optional = true, version = "0.0.8" }
h3-datagram = { default-features = false, optional = true, version = "0.0.2" }
h3-quinn = { default-features = false, optional = true, version = "0.0.10" }
h3-webtransport = { default-features = false, optional = true, version = "0.1" }
quinn = { default-features = false, features = ["platform-verifier", "runtime-tokio", "rustls-aws-lc-rs"], optional = true, version = "0.11" }

# TLS
tokio-rustls = { default-features = false, features = ["aws_lc_rs", "tls12"], optional = true, version = "0.26" }

# Tower Services
tower = { default-features = false, features = ["make"], optional = true, version = "0.5" }

document-features = { optional = true, version = "0.2" }
scuffle-changelog = { optional = true, path = "../changelog", version = "0.1" }

[dev-dependencies]
# The http3 feature requires a custom build flag (see .cargo/config.toml)
axum = { features = ["ws"], version = "0.8" }
reqwest = { default-features = false, features = ["http2", "http3-aws-lc-rs", "rustls-tls-no-provider"], version = "0.12" }
scuffle-future-ext = { path = "../future-ext" }
tokio-test = "0.4"

# For examples:
tokio = { features = ["full"], version = "1" }
tracing = { version = "0.1" }
tracing-subscriber = { features = ["env-filter"], version = "0.3" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg",
    "docsrs",
    "--sort-modules-by-appearance",
    "--generate-link-to-definition",
]

[package.metadata.xtask.powerset]
additive-features = ["tracing", "tower", "docs"]
ignore-features = ["http3"]

[package.metadata.sync-readme.rustdoc-mappings]
changelog = "./CHANGELOG.md"

[package.metadata.sync-readme.badges]
docs-rs = true
crates-io = true
license = true
codecov = true
