name: Security audit
on:
  push:
    branches-ignore:
      - "automation/**"
    paths:
      - ".github/workflows/audit.yaml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
  schedule:
    - cron: "0 0 * * *"

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: "stable"
