name: cargo deny
on:
  push:
    branches-ignore:
      - "automation/**"
    paths:
      - ".github/workflows/cargo-deny.yaml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubicloud-standard-8-ubuntu-2404
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-bazel
        with:
          build_buddy_token: ${{ secrets.build_buddy_token }}

      - name: Check
        run: bazel run //tools/cargo/deny check
