name: cargo test

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends clang curl pkg-config xz-utils libxv-dev ninja-build meson nasm protobuf-compiler
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        id: setup-rust
        with:
          cache: false
          toolchain: nightly
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
          key: test

      - uses: cargo-bins/cargo-binstall@main

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov,just,cargo-insta

      - run: just test-ci

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./target/nextest/ci/junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}
