name: cargo fmt

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  fmt:
    name: Fmt
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: -D warnings
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        id: setup-rust
        with:
          cache: false
          toolchain: nightly
          components: rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
          key: fmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
