name: cargo clippy

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: -D warnings
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends clang curl pkg-config xz-utils libxv-dev ninja-build meson nasm protobuf-compiler
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        id: setup-rust
        with:
          cache: false
          toolchain: nightly
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
          key: clippy

      - uses: auguwu/clippy-action@1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
