name: Test

on:
  workflow_call:
    inputs:
      matrix:
        type: string
    secrets:
      codecov_token:
        required: true
      build_buddy_token:
        required: true

defaults:
  run:
    shell: bash

jobs:
  grind:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/download-artifact@v5
        if: ${{ github.event_name == 'pull_request' }}
        with:
            name: bazel-diff-impacted-targets

      - uses: ./.github/actions/setup-bazel
        with:
          build_buddy_token: ${{ secrets.build_buddy_token }}

      - name: Install libc6-dbg
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install libc6-dbg -y

      - name: Run tests with valgrind
        run: |
          bazel query 'kind("nextest_test rule", set(//...))' > all_targets.txt

          if [ -f ./impacted-targets.txt ]; then
            targets=$(python3 ./.github/scripts/ci-targets.py ./all_targets.txt ./impacted-targets.txt)
          else
            targets=$(cat all_targets.txt)
          fi

          # Exit early if no targets
          if [ -z "$targets" ]; then
            echo "No targets to test."
            exit 0
          fi

          bazel test ${targets} --//settings:test_rustc_flags="--cfg=valgrind" --//settings:test_valgrind --skip_incompatible_explicit_targets
