name: Test

on:
  workflow_call:
    inputs:
      matrix:
        type: string
    secrets:
      codecov_token:
        required: true
      build_buddy_token:
        required: true

defaults:
  run:
    shell: bash

jobs:
  grind:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bazel
        with:
          build_buddy_token: ${{ secrets.build_buddy_token }}

      - name: Install libc6-dbg
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install libc6-dbg -y

      - name: Run tests with valgrind
        run: |
          targets=$(bazel cquery 'kind("nextest_test rule", set(//...))' --output=starlark --starlark:expr='target.label')
          bazel test ${targets} --//settings:test_rustc_flags="--cfg=valgrind" --//settings:test_valgrind
