name: ci - rustdoc

on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
      deploy_docs:
        type: boolean
      pr_number:
        type: string
        required: true
      commit_sha:
        type: string
        required: true
    secrets:
      build_buddy_token:
        required: true
      cf_api_key:
        required: false
      cf_account_id:
        required: false

defaults:
  run:
    shell: bash

jobs:
  rustdoc:
    runs-on: ubicloud-standard-8-ubuntu-2404
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bazel
        with:
          build_buddy_token: ${{ secrets.build_buddy_token }}

      - name: Build
        run: bazel build //docs:rustdoc

      - name: Upload
        uses: actions/upload-artifact@v4
        if: ${{ inputs.artifact_name }}
        with:
          name: ${{ inputs.artifact_name }}
          path: ./target-bazel/bin/docs/rustdoc.rustdoc_merge

      - name: Deploy
        if: ${{ inputs.deploy_docs }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.cf_api_key }}
          packageManager: npm
          accountId: ${{ secrets.cf_account_id }}
          command: pages deploy --project-name=scuffle-docrs --branch=pr/${{ inputs.pr_number }} --commit-hash=${{ inputs.commit_sha }} ./target-bazel/bin/docs/rustdoc.rustdoc_merge
