name: ci - rustdoc

on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
      deploy_docs:
        type: boolean
      pr_number:
        type: string
        required: true
      commit_sha:
        type: string
        required: true
    secrets:
      build_buddy_token:
        required: true
      netlify_site_id:
        required: false
      netlify_auth_token:
        required: false

defaults:
  run:
    shell: bash

jobs:
  rustdoc:
    runs-on: ubicloud-standard-8-ubuntu-2404
    steps:
      - uses: actions/checkout@v4

      - name: Install zstd
        run: apt-get update && apt-get install zstd -y

      - uses: ./.github/actions/setup-bazel
        with:
          build_buddy_token: ${{ secrets.build_buddy_token }}

      - name: Build
        run: bazel build //docs:rustdoc

      - name: Compress docs
        run: |
          cd ./target-bazel/bin/docs/rustdoc.rustdoc_merge
          tar -cf - * | zstd --ultra -22 -o "../../../../rustdoc.tar.zst"

      - name: Upload
        uses: actions/upload-artifact@v4
        if: ${{ inputs.artifact_name }}
        with:
          name: ${{ inputs.artifact_name }}
          path: rustdoc.tar.zst

      - name: Deploy
        if: ${{ inputs.deploy_docs }}
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./target-bazel/bin/docs/rustdoc.rustdoc_merge
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Preview for PR #${{ github.event.number }}"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: pr-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.netlify_auth_token }}
          NETLIFY_SITE_ID: ${{ secrets.netlify_site_id }}
