name: ci

on:
  push:
    branches:
      - automation/brawl/try/*
      - automation/brawl/merge/*

  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}

defaults:
  run:
    shell: bash

jobs:
  prep:
    name: prep
    runs-on: ubuntu-24.04
    outputs:
      prep: ${{ steps.compute.outputs.prep }}
    steps:
      - uses: actions/checkout@v4

      - name: Run prep
        id: compute
        env:
          JSON_INPUT: ${{ toJson(github) }}
        run: |
          set -xeo pipefail
          echo $JSON_INPUT | python3 .github/scripts/ci-prep.py | tee -a $GITHUB_OUTPUT

  check_vendor:
    needs: [prep]
    if: ${{ fromJson(needs.prep.outputs.prep).check_vendor != null }}
    uses: ./.github/workflows/ci-check-vendor.yaml
    secrets:
      build_buddy_token: ${{ secrets.BUILD_BUDDY_TOKEN }}

  test:
    needs: [prep]
    if: ${{ fromJson(needs.prep.outputs.prep).test != null }}
    uses: ./.github/workflows/ci-test.yaml
    with:
      commit_sha: "${{ fromJson(needs.prep.outputs.prep).test.commit_sha }}"
      pr_number: "${{ fromJson(needs.prep.outputs.prep).test.pr_number }}"
      matrix: "${{ toJson(fromJson(needs.prep.outputs.prep).test.matrix) }}"
    secrets:
      codecov_token: "${{ secrets.CODECOV_TOKEN }}"
      build_buddy_token: "${{ secrets.BUILD_BUDDY_TOKEN }}"

  check_fmt:
    needs: [prep]
    if: ${{ fromJson(needs.prep.outputs.prep).check_fmt != null }}
    uses: ./.github/workflows/ci-check-fmt.yaml
    secrets:
      build_buddy_token: ${{ secrets.BUILD_BUDDY_TOKEN }}

  grind:
    needs: [prep]
    if: ${{ fromJson(needs.prep.outputs.prep).grind != null }}
    uses: ./.github/workflows/ci-grind.yaml
    with:
      matrix: "${{ toJson(fromJson(needs.prep.outputs.prep).grind.matrix) }}"
    secrets:
      codecov_token: "${{ secrets.CODECOV_TOKEN }}"
      build_buddy_token: "${{ secrets.BUILD_BUDDY_TOKEN }}"

  rustdoc:
    needs: [prep]
    if: ${{ fromJson(needs.prep.outputs.prep).rustdoc != null }}
    uses: ./.github/workflows/ci-rustdoc.yaml
    with:
      artifact_name: "${{ fromJson(needs.prep.outputs.prep).rustdoc.artifact_name }}"
      commit_sha: "${{ fromJson(needs.prep.outputs.prep).rustdoc.commit_sha }}"
      pr_number: "${{ fromJson(needs.prep.outputs.prep).rustdoc.pr_number }}"
      deploy_docs: "${{ fromJson(needs.prep.outputs.prep).rustdoc.deploy_docs }}"
    secrets:
      build_buddy_token: "${{ secrets.BUILD_BUDDY_TOKEN }}"
      vercel_token: "${{ secrets.VERCEL_TOKEN }}"
      vercel_project_id: "${{ secrets.VERCEL_PROJECT_ID_DOCS_SCUFFLE_RS }}"
      vercel_org_id: "${{ secrets.VERCEL_ORG_ID }}"

  brawl-done:
    runs-on: ubuntu-24.04
    needs: [check_vendor, test, check_fmt, grind, rustdoc]
    if: ${{ !cancelled() && github.event_name == 'push' }}
    steps:
      - name: calculate the correct exit status
        run: jq --exit-status 'all(.result == "success" or .result == "skipped")' <<< '${{ toJson(needs) }}'
