name: ci

on:
  push:
    branches:
      - automation/brawl/try/*
      - automation/brawl/merge/*

  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  prep:
    name: Prep
    runs-on: ubuntu-24.04
    outputs:
      prep: ${{ fromJson(steps.compute.outputs.prep) }}
    steps:
      - uses: actions/checkout@v4

      - name: Switch to Branch
        run: |
          set -xeo pipefail
          git switch -C ${{ github.ref_name }}

      - name: Run prep
        id: compute
        env:
          JSON_INPUT: ${{ toJson(github) }}
        run: |
          set -xeo pipefail
          echo $JSON_INPUT | python3 .github/scripts/ci-prep.py | tee -a $GITHUB_OUTPUT

  check_vendor:
    needs: [prep]
    if: ${{ needs.prep.outputs.prep['check_vendor'] != null }}
    uses: ./.github/workflows/ci-check-vendor.yaml
    secrets:
      build_buddy_token: ${{ secrets.BUILD_BUDDY_TOKEN }}

  test:
    needs: [prep]
    if: ${{ needs.prep.outputs.prep['test'] != null }}
    uses: ./.github/workflows/ci-test.yaml
    with:
      commit_sha: ${{ needs.prep.outputs.prep['test']['commit_sha'] }}
      pr_number: ${{ needs.prep.outputs.prep['test']['pr_number'] }}
      matrix: ${{ toJson(needs.prep.outputs.prep['test']['matrix']) }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      build_buddy_token: ${{ secrets.BUILD_BUDDY_TOKEN }}

  grind:
    needs: [prep]
    if: ${{ needs.prep.outputs.prep['grind'] != null }}
    uses: ./.github/workflows/ci-grind.yaml
    with:
      commit_sha: ${{ needs.prep.outputs.prep['grind']['commit_sha'] }}
      pr_number: ${{ needs.prep.outputs.prep['grind']['pr_number'] }}
      matrix: ${{ toJson(needs.prep.outputs.prep['grind']['matrix']) }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      build_buddy_token: ${{ secrets.BUILD_BUDDY_TOKEN }}

  rustdoc:
    needs: [prep]
    if: ${{ needs.prep.outputs.prep['rustdoc'] != null }}
    uses: ./.github/workflows/ci-rustdoc.yaml
    secrets:
      build_buddy_token: ${{ secrets.BUILD_BUDDY_TOKEN }}

  brawl-done:
    runs-on: ubuntu-24.04
    needs: [check_vendor, test, grind, rustdoc]
    if: ${{ !cancelled() && github.event_name == 'push' }}
    steps:
      - name: calculate the correct exit status
        run: jq --exit-status 'all(.result == "success" or .result == "skipped")' <<< '${{ toJson(needs) }}'
