name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release

jobs:
  crates-io:
    name: Crates.io
    runs-on: ubuntu-24.04
    environment: crates.io
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup FFmpeg
        uses: ./.github/actions/setup-ffmpeg

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: fregante/setup-git-user@v2

      - name: Fetch History
        shell: bash
        run: |
          git fetch --unshallow

      - name: Run release
        env:
          GH_TOKEN: ${{ github.token }}
        run: cargo xtask release publish --crates-io-token ${{ secrets.CARGO_REGISTRY_TOKEN }}

  docs-rs:
    name: Docs.rs
    runs-on: ubuntu-24.04
    environment: docs.scuffle.rs
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: ci.yaml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: docsrs
          path: target/doc

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: npm
          apiToken: ${{ secrets.CF_DOCS_API_KEY }}
          accountId: ${{ secrets.CF_DOCS_ACCOUNT_ID }}
          command: pages deploy --project-name=scuffle-docrs --branch=main --commit-hash=${{ github.sha }} --commit-dirty=true ./target/doc

  docusaurus:
    name: Docusaurus
    runs-on: ubuntu-24.04
    environment: docs.scuffle.cloud
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: ci.yaml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: docusaurus
          path: docs/build

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: npm
          apiToken: ${{ secrets.CF_DOCS_API_KEY }}
          accountId: ${{ secrets.CF_DOCS_ACCOUNT_ID }}
          command: pages deploy --project-name=scuffle-docusaurus-docs --branch=main --commit-hash=${{ github.sha }} --commit-dirty=true ./docs/build
